title: Github Actions Sandbox
url: "https://noraworld.github.io"
baseurl: "/github-actions-sandbox"
permalink: /:title/

theme: minima
markdown: CommonMark
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-commonmark

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .gitignore
  - README.md
  - package.json
  - package-lock.json
  - .ruby-version
  - .rubocop.yml
  - CNAME
