# tmp
# with.repository

name: Build Jekyll with customizable environments

inputs:
  use_ruby_version:
    required: false
    default: false
  use_gemfile:
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - if: ${{ !(inputs.use_ruby_version == 'true' && inputs.use_gemfile == 'true') }}
      name: Check if tmp directory is excluded in _config.yml
      run: |
        if ! sed -n '/^exclude:/,/^[^[:space:]]/p' _config.yml | grep -qE '^\s*-\s*tmp'; then
          echo "Error: tmp is not excluded in _config.yml" >&2
          exit 1
        fi
      shell: sh

    - if: ${{ !(inputs.use_ruby_version == 'true' && inputs.use_gemfile == 'true') }}
      name: Check out Action repository
      uses: actions/checkout@v4
      with:
        repository: noraworld/github-actions-sandbox
        ref: main
        path: tmp

    - name: Set environments
      run: |
        if [ "${{ inputs.use_ruby_version }}" = "true" ]; then
          echo "RUBY_VERSION=$(cat .ruby-version)" >> $GITHUB_ENV
        else
          echo "RUBY_VERSION=$(cat tmp/.ruby-version)" >> $GITHUB_ENV
        fi

        if [ "${{ inputs.use_gemfile }}" = "true" ]; then
          echo "BUNDLE_GEMFILE=$(realpath Gemfile)" >> $GITHUB_ENV
        else
          echo "BUNDLE_GEMFILE=$(realpath tmp/Gemfile)" >> $GITHUB_ENV
        fi
      shell: sh

    - name: Set up Pages
      uses: actions/configure-pages@v5

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
        rubygems: latest

    - name: Build with Jekyll
      run: bundle exec jekyll build
      shell: sh

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
