name: ディスパッチの入力値がログに表示されるを防ぎたい！

on:
  workflow_dispatch:
    inputs:
      foo:
        required: false
        description: https://github.com
        type: string
      bar:
        required: false
        description: 'https://github.com'
        type: string
      baz:
        required: false
        description: '[GitHub](https://github.com)'
        type: string
      qux:
        required: false
        description: 'qux'
        type: string
      quux:
        required: false
        description: 'quux'
        type: string
      corge:
        required: false
        description: 'corge'
        type: string
      grault:
        required: false
        description: 'grault'
        type: string
      garply:
        required: false
        description: 'garply'
        type: string
      waldo:
        required: false
        description: 'waldo'
        type: string
      fred:
        required: false
        description: 'fred'
        type: string

jobs:
  dispatch-inputs-call:
    uses: noraworld/github-actions-sandbox/.github/workflows/dispatch-inputs-call.yml@main
