name: ディスパッチの入力値がログに表示されるを防ぎたい！

on:
  workflow_dispatch:
    inputs:
      foo:
        required: true
        description: '入力値'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: noraworld/github-actions-sandbox/.github/workflows/dispatch-inputs-call.yml@main
