name: main

on:
  workflow_dispatch:

jobs:
  daily-report-day-off:
    uses: noraworld/diary-templates-assistant/.github/workflows/day-off.yml@main
    with:
      fail_if_day_off: false
      gh_output_format: true
      timezone: 'Asia/Tokyo'

  check-if-skipped:
    needs: daily-report-day-off
    if: needs.daily-report-day-off.outputs.day_off == 'false'
    run: |
      echo "it works!"
