name: Post to note and commit note_id

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Post to note
        uses: noraworld/github-to-note@main
        with:
          note_email: ${{ secrets.NOTE_EMAIL }}
          note_password: ${{ secrets.NOTE_PASSWORD }}
          content_file: ./_posts/ja/2026/02/2026-02-25-sample.md
          write_note_id: "true"

      - name: Commit updated note_id
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./_posts/ja/2026/02/2026-02-25-sample.md
          git diff --cached --quiet || git commit -m "chore: write note_id"
          git push
