name: Post to note from file

on:
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Post to note
        uses: noraworld/github-to-note@main
        with:
          note_email: ${{ secrets.NOTE_EMAIL }}
          note_password: ${{ secrets.NOTE_PASSWORD }}
          title: 朝の coffee を少し変えてみた話
          content_file: ./_posts/ja/2026/02/_posts/ja/2026/02/2026-02-25-sample.md
